sudo: required
dist: trusty

language: node_js

node_js:
    - "4"
    - "5"
    - "6"

env:
    - NODE_ENV=development

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

before_install:
    - npm install -g yarn

install:
    - yarn install
    - cd tests && yarn install

cache:
    yarn: true

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm test