language: node_js

node_js:
    - "4"
    - "5"
    - "6"

env:
    - NODE_ENV=development

before_install:
    - npm install -g yarn

install:
    - yarn install
    - cd tests && yarn install

cache:
    yarn: true

before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm test